remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//fp-ts.github.io/core"
  "API Reference":
    - "//fp-ts.github.io/core/docs/modules"
  "GitHub":
    - "//github.com/fp-ts/core"
